from __future__ import annotations
from datetime import datetime, timedelta
import dotenv
dotenv.load_dotenv()
from langsmith import traceable
import json
import logging
import orjson
import os
import shlex
import shutil
import subprocess
import sys
import time
import signal
import selectors
from pathlib import Path
from typing import Any, Callable
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage

from langchain_openrouter import ChatOpenRouter


CHAT_MODEL = os.getenv("CHAT_MODEL", "openai/gpt-5.4")
CHAT_REASONING_EFFORT = os.getenv("CHAT_REASONING_EFFORT", "medium")

CODEX_MODEL = os.getenv("CODEX_MODEL", "gpt-5.4")
CODEX_REASONING_EFFORT = os.getenv("CODEX_REASONING_EFFORT", "high")


def _codex_bypass_sandbox() -> bool:
    v = (os.getenv("CODEX_BYPASS_SANDBOX") or "").strip().lower()
    return v in ("1", "true", "yes", "on")

CODE_ANALYSIS_MODEL = os.getenv("CODE_ANALYSIS_MODEL", "anthropic/claude-opus-4.7")

SYSTEM_PROMPT = f"""You help users design trading strategies in chat.

Workflow

* Before the first update_strategy, request any missing details needed to build the strategy (e.g., ticker, candlestick scale, backtest window (start/end dates), indicators, entry/exit rules, order sizing, other parameters). The user may want to come up with good default values for these parameters, proceed with good defaults then. 
* Do not add hyperparameter search loops inside strategy.py by default; optimization is driven by the fixed workspace script hyperopt.py when the user asks for it.
* To modify code call update_strategy with a brief task describing only the changes. Use english for the task description.
* If the user only tweaks existing parameters (different ticker, dates, thresholds, deposit, etc.), call run_backtest instead of update_strategy; pass parameters_json as a JSON string so the tool recursively merges into params.json before the run (do not use a --params CLI flag or teach strategies to accept one).
* If the user asks for exploratory data analysis, market research, or charts **without** defining a tradable strategy (no signals, no rules backtest), use `update_strategy` for the analysis path, then run_backtest. That path must not write metrics.json or params-hyperopt.json.
* If the user asks for training/hyperparameter optimization, ensure via update_strategy that the strategy workspace writes params-hyperopt.json (authored as a static file per the workspace AGENTS.md), then run_hyperopt (not run_backtest). To adjust the study without editing files—how many strategy parameters are tuned, their optimisation ranges and bounds, regimes or other study-only config—pass parameters_hyperopt_json on run_hyperopt to merge into params-hyperopt.json before the run.
* Always respond in the user's language.
* After each successful update_strategy, call run_backtest or run_hyperopt so results match the change. Only briefly summarize strategy performance based on the output of that tool call, don't make up numbers. The user already sees all the charts and metrics.

Notes
* The workspace follows strategies_v2 conventions (see AGENTS.md there): strategy.py is a streaming process that reads params.json, emits ticker_subscription and indicator_subscription on startup, then processes StrategyInput lines from stdin and emits market_order / indicator / time_ack outputs on stdout. utils.py and hyperopt.py are fixed and must not be edited.
* update_strategy edits strategy.py, params.json, and (for trading strategies) params-hyperopt.json via the coding agent; layout and run contract follow AGENTS.md in that workspace.
* run_backtest runs the historical simulator (scripts/simulate_strategy_v2.py): it fetches OHLC bars for the ticker/scale across start_date..end_date from params.json, streams them to strategy.py, and refreshes backtest.json (charts) and metrics.json (scalar metrics).
* run_hyperopt runs the random-search hyperparameter study in the workspace, which invokes the same simulator per trial and rewrites params.json with the best trial before a final simulator run.
* Market data providers: use Alpaca for all non-Russian markets; use MOEX (moexalgo/Algopack) for Russian instruments/markets.
* Alpaca historical market data starts in 2016; there is no data before 2016.
* Auto provider selection is allowed and preferred when uncertain: try Alpaca first, then MOEX.
* Do not use yfinance or ask the user to switch to yfinance.
* Backtesting via simulation is supported; live trading is not.
* Do NOT share with the user specific details about how the strategy is implemented (python code generated by the coding agent).
* Today's date is {(datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")}.

{{strategy_help}}

Answer in plain text. No JSON or markup unless the user asks."""

STRATEGIES_DIR = Path(__file__).resolve().parents[1] / "strategies_v2"
STRATEGY_AGENTS_TEMPLATE = STRATEGIES_DIR / "AGENTS.md"
STRATEGY_CODE_TEMPLATE = STRATEGIES_DIR / "strategy.py"
STRATEGY_UTILS_TEMPLATE = STRATEGIES_DIR / "utils.py"
STRATEGY_PARAMS_TEMPLATE = STRATEGIES_DIR / "params.json"
STRATEGY_HYPEROPT_TEMPLATE = STRATEGIES_DIR / "hyperopt.py"
SIMULATE_SCRIPT_PATH = Path(__file__).resolve().parents[1] / "scripts" / "simulate_strategy_v2.py"
STRATEGY_CODE_AGENT_PREFIX = ""
UPDATE_STRATEGY_TOOL_NAME = "update_strategy"
RUN_BACKTEST_TOOL_NAME = "run_backtest"
RUN_HYPEROPT_TOOL_NAME = "run_hyperopt"
UPDATE_STRATEGY_TOOL_MESSAGE_MAX_JSON = 1024
RUN_EXECUTION_TOOL_MESSAGE_MAX_JSON = 4096
ANALYSE_CODE_TOOL_NAME = "analyse_code"

ProgressCallback = Callable[[str], None] | None

CODING_TOOL = 'codex'

logger = logging.getLogger(__name__)


@traceable(name="run_logged_subprocess")
def _run_logged_subprocess(
    label: str,
    cmd: list[str],
    cwd: str,
    *,
    timeout: int,
) -> subprocess.CompletedProcess[str]:
    try:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
    except subprocess.TimeoutExpired as e:
        logger.error("%s timed out after %s seconds", label, e.timeout)
        raise
    except OSError as e:
        logger.error("%s failed to start: %s", label, e)
        raise
    if proc.returncode != 0:
        logger.error(
            "%s failed: returncode=%s\nstdout:\n%s\nstderr:\n%s",
            label,
            proc.returncode,
            _tail(proc.stdout or ""),
            _tail(proc.stderr or ""),
        )
    return proc


def thread_id_allowed(thread_id: str) -> bool:
    tid = (thread_id or "").strip()
    if not tid:
        return False
    if tid != thread_id:
        return False
    for bad in ("..", "/", "\\"):
        if bad in tid:
            return False
    return True


def _chmod_readonly(path: Path) -> None:
    try:
        path.chmod(0o444)
    except OSError:
        logger.warning("could not set read-only mode on %s", path)


def ensure_strategy_workspace(thread_id: str) -> Path:
    if not thread_id_allowed(thread_id):
        raise ValueError("invalid thread_id")
    workspace = STRATEGIES_DIR / thread_id
    workspace.mkdir(parents=True, exist_ok=True)
    dest_agents = workspace / "AGENTS.md"
    if not dest_agents.is_file() and STRATEGY_AGENTS_TEMPLATE.is_file():
        shutil.copy2(STRATEGY_AGENTS_TEMPLATE, dest_agents)
    dest_strategy = workspace / "strategy.py"
    if not dest_strategy.is_file() and STRATEGY_CODE_TEMPLATE.is_file():
        shutil.copy2(STRATEGY_CODE_TEMPLATE, dest_strategy)
    dest_params = workspace / "params.json"
    if not dest_params.is_file() and STRATEGY_PARAMS_TEMPLATE.is_file():
        shutil.copy2(STRATEGY_PARAMS_TEMPLATE, dest_params)
    for template, name in (
        (STRATEGY_UTILS_TEMPLATE, "utils.py"),
        (STRATEGY_HYPEROPT_TEMPLATE, "hyperopt.py"),
    ):
        if not template.is_file():
            continue
        dest = workspace / name
        if dest.is_file():
            try:
                dest.chmod(0o644)
            except OSError:
                logger.warning("could not make writable for refresh: %s", dest)
        shutil.copy2(template, dest)
        _chmod_readonly(dest)
    return workspace


def strategy_root_for_thread(thread_id: str) -> Path:
    return ensure_strategy_workspace(thread_id)


def read_strategy_code(thread_id: str) -> str:
    root = ensure_strategy_workspace(thread_id)
    path = root / "strategy.py"
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def read_strategy_utils(thread_id: str) -> str:
    root = ensure_strategy_workspace(thread_id)
    path = root / "utils.py"
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8", errors="replace")


def restore_strategy_workspace_from_snapshot(
    thread_id: str,
    *,
    code: str | None,
    canvas: dict[str, Any] | None,
) -> None:
    root = ensure_strategy_workspace(thread_id)

    (root / "strategy.py").write_text(code or "", encoding="utf-8")

    for name in CANVAS_OUTPUT_FILES:
        path = root / name
        try:
            if path.is_file():
                path.unlink()
        except OSError:
            pass

    if not isinstance(canvas, dict):
        return
    output = canvas.get("output")
    if not isinstance(output, dict):
        return

    for filename, contents in output.items():
        if not isinstance(filename, str) or filename not in CANVAS_OUTPUT_FILES:
            continue
        out_path = root / filename
        if isinstance(contents, (dict, list)) and out_path.suffix.lower() == ".json":
            out_path.write_text(json.dumps(contents, indent=2, sort_keys=True), encoding="utf-8")
        elif isinstance(contents, str):
            out_path.write_text(contents, encoding="utf-8")
        else:
            out_path.write_text(str(contents), encoding="utf-8")

AGENT_TOOLS: list[dict[str, Any]] = [
    {
        "type": "function",
        "function": {
            "name": UPDATE_STRATEGY_TOOL_NAME,
            "description": (
                "Implement strategy or analysis changes in this thread's strategy workspace using the configured coding agent. "
                "Workspace conventions are in AGENTS.md there. After it succeeds, call run_backtest or run_hyperopt to refresh outputs."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "task": {
                        "type": "string",
                        "description": (
                            "High-level goal and required behavior or code changes only; use english for the task description."
                            "Do not specify any file paths or filenames, the tool already known them"
                        ),
                    }
                },
                "required": ["task"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": RUN_BACKTEST_TOOL_NAME,
            "description": (
                "Run a single backtest in this thread's workspace (no coding agent, no code edits). "
                "Dispatches to scripts/simulate_strategy_v2.py: fetches OHLC bars for the ticker/scale across "
                "start_date..end_date from params.json, streams them to strategy.py, and refreshes backtest.json and metrics.json. "
                "Optional parameters_json (a JSON string) is recursively merged into params.json before the run."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "parameters_json": {
                        "type": "string",
                        "description": (
                            "If provided, must be valid JSON. Object values are merged recursively into existing params.json "
                            "(nested dicts merged by key, lists merged by index with recursive dict merge where both sides are objects; "
                            "scalars and mismatched types take the new value). Non-object JSON replaces the file."
                        ),
                    },
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": RUN_HYPEROPT_TOOL_NAME,
            "description": (
                "Run hyperparameter optimization in this thread's workspace (no coding agent, no code edits). "
                "Requires a valid params-hyperopt.json. Invokes the same simulator per trial and rewrites params.json "
                "with the best trial before a final simulator run. "
                "Optional parameters_json (a JSON string) is merged into params.json before the study. "
                "Optional parameters_hyperopt_json (a JSON string) is merged into params-hyperopt.json before the study "
                "(study definition: which params are optimised, their ranges, regimes, trial budget, etc.—not base backtest inputs like ticker or dates; use parameters_json for those)."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "parameters_json": {
                        "type": "string",
                        "description": (
                            "If provided, must be valid JSON. Object values are merged recursively into existing params.json "
                            "before hyperopt starts, using the same merge rules as run_backtest."
                        ),
                    },
                    "parameters_hyperopt_json": {
                        "type": "string",
                        "description": (
                            "If provided, must be valid JSON. Merged recursively into existing params-hyperopt.json (same merge rules as "
                            "parameters_json into params.json). Use this to change the optimisation study: which strategy parameters are "
                            "in the search space, their ranges or bounds, regimes, trial count or timeouts, and other study-only settings—not "
                            "base simulation inputs in params.json (ticker, dates, deposit, etc.); pass those via parameters_json."
                        ),
                    },
                },
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": ANALYSE_CODE_TOOL_NAME,
            "description": (
                "Answer a question about the current strategy's code (strategy.py, utils.py, hyperopt.py) "
                "and params in this thread. "
                "Use for quick code comprehension without modifying files."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "question": {
                        "type": "string",
                        "description": "A natural-language question about the current strategy code.",
                    }
                },
                "required": ["question"],
            },
        },
    },
]


def _tail(s: str, max_chars: int = 12_000) -> str:
    if len(s) <= max_chars:
        return s
    return s[-max_chars:]


def _trim_tool_payload_streams(
    payload: dict[str, Any],
    max_json_len: int,
    out_key: str,
    err_key: str,
) -> dict[str, Any]:
    out = dict(payload)
    if max_json_len <= 0:
        out[out_key] = ""
        out[err_key] = ""
        return out
    out[out_key] = _tail(str(out.get(out_key, "") or ""), max_json_len)
    out[err_key] = _tail(str(out.get(err_key, "") or ""), max_json_len)
    return out


def _read_strategy_params_text(thread_id: str) -> str:
    root = ensure_strategy_workspace(thread_id)
    params_path = root / "params.json"
    if not params_path.is_file():
        return ""
    try:
        return params_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


@traceable(name="run_analyse_code")
def run_analyse_code(
    *,
    thread_id: str,
    question: str,
) -> dict[str, Any]:
    q = (question or "").strip()
    if not q:
        return {"ok": False, "error": "question is empty"}
    if not thread_id_allowed(thread_id):
        return {"ok": False, "error": "invalid thread_id"}
    if not os.getenv("OPENROUTER_API_KEY", "").strip():
        return {"ok": False, "error": "OPENROUTER_API_KEY is not configured"}

    code = read_strategy_code(thread_id)
    utils_text = read_strategy_utils(thread_id)
    params_text = _read_strategy_params_text(thread_id)

    analysis_system = (
        "You are a code analyst for a trading strategy project. "
        "Answer the user's question using ONLY the provided strategy code, utils.py, and params. "
        "Be concise: 1-4 sentences. If the answer cannot be determined, say what is missing."
    )
    context = (
        "Strategy params (JSON, may be empty):\n"
        f"{params_text if params_text else ''}\n\n"
        "utils.py (Python, may be empty):\n"
        f"{utils_text if utils_text else ''}\n\n"
        "strategy.py (Python, may be empty):\n"
        f"{code if code else ''}"
    )

    llm = ChatOpenRouter(model=CODE_ANALYSIS_MODEL, request_timeout=120_000)
    msg = llm.invoke(
        [
            SystemMessage(content=analysis_system),
            SystemMessage(content=context),
            HumanMessage(content=q),
        ]
    )
    answer = _aimessage_plain_text(msg).strip()
    return {"ok": True, "answer": answer}


@traceable(name="generate_strategy_algorithm_pseudocode")
def generate_strategy_algorithm_pseudocode(*, code: str, language: str = "") -> dict[str, Any]:
    src = (code or "").strip()
    if not src:
        return {
            "ok": True,
            "algorithm": "No strategy source code was saved for this run.",
        }
    if not os.getenv("OPENROUTER_API_KEY", "").strip():
        return {"ok": False, "error": "OPENROUTER_API_KEY is not configured"}

    lang = (language or "").strip().lower()
    lang_line = (
        f"The user's conversation language (ISO 639-1) is {lang}. Write all natural-language explanations, "
        f"step titles, and comments in that language."
        if lang
        else "The user's conversation language is unknown; write all natural-language explanations, step titles, and comments in English."
    )
    system = (
        "Write very compact, language-agnostic pseudocode for the core business logic of this trading strategy only. "
        "Omit boilerplate entirely: CLI/argparse, imports, logging, file I/O, HTTP/API calls, "
        "dataframe plumbing, plotting, JSON/chart serialization, and generic helpers unless they directly encode a trading rule. "
        "Do NOT include or rewrite the pseudocode of internal logic for standard indicators (like RSI, MACD, etc) — if strategy uses a standard indicator, mention its use without describing or outlining its internal computation. "
        "No long code quotes. Prefer tight numbered steps or compact bullets. If something essential is ambiguous in the source, "
        "state the single most likely interpretation in one line. "
        "Can use Markdown for formatting. "
        + lang_line
    )
    llm = ChatOpenRouter(model=CODE_ANALYSIS_MODEL, request_timeout=120_000)
    msg = llm.invoke(
        [
            SystemMessage(content=system),
            HumanMessage(
                content="Extract core-algorithm pseudocode from this strategy.py (business logic only, no I/O boilerplate).\n\n"
                + src
            ),
        ]
    )
    text = _aimessage_plain_text(msg).strip()
    return {"ok": True, "algorithm": text or "(empty response)"}


CANVAS_OUTPUT_FILES: frozenset[str] = frozenset(
    {
        "params.json",
        "backtest.json",
        "metrics.json",
        "params-hyperopt.json",
    }
)

CANVAS_OUTPUT_KEYS: frozenset[str] = CANVAS_OUTPUT_FILES | frozenset({"strategy_cli_description"})


def _read_strategy_workspace_files(thread_id: str) -> dict[str, Any]:
    root = strategy_root_for_thread(thread_id)
    out: dict[str, Any] = {}
    for name in CANVAS_OUTPUT_FILES:
        path = root / name
        if not path.is_file():
            continue
        raw = path.read_text(encoding="utf-8", errors="replace")
        if path.suffix.lower() == ".json":
            try:
                out[name] = json.loads(raw)
            except json.JSONDecodeError:
                out[name] = raw
        else:
            out[name] = raw
    return out


def sanitize_json_for_postgres(value: Any) -> Any:
    return orjson.loads(
        orjson.dumps(value, option=orjson.OPT_SERIALIZE_NUMPY)
    )


def canvas_with_output(existing_canvas: dict[str, Any], thread_id: str) -> dict[str, Any]:
    merged = dict(existing_canvas)
    if thread_id_allowed(thread_id):
        existing_output = merged.get("output")
        if not isinstance(existing_output, dict):
            existing_output = {}
        filtered_existing = {k: v for k, v in existing_output.items() if k in CANVAS_OUTPUT_KEYS}
        disk_output = _read_strategy_workspace_files(thread_id)
        merged["output"] = {**filtered_existing, **disk_output}
        workspace = strategy_root_for_thread(thread_id)
        desc = read_strategy_description_from_workspace(workspace)
        out = merged["output"]
        if desc:
            out["strategy_cli_description"] = desc
        else:
            out.pop("strategy_cli_description", None)
    else:
        merged["output"] = {}
    return sanitize_json_for_postgres(merged)


@traceable(name="run_codex_exec")
def _run_codex_exec(task: str, cwd: Path) -> subprocess.CompletedProcess[str]:
    root = str(cwd.resolve())
    sandbox_flag = (
        "--dangerously-bypass-approvals-and-sandbox"
        if _codex_bypass_sandbox()
        else "--full-auto"
    )
    cmd = [
        "codex",
        "exec",
        sandbox_flag,
        "-C",
        root,
        "--skip-git-repo-check",
        "-c", "service_tier=fast",
        "-c", f"model={CODEX_MODEL}",
        "-c", "model_verbosity=low",
        "-c", f"model_reasoning_effort={CODEX_REASONING_EFFORT}", # minimal, low, medium, high, xhigh
        "-c", "features.fast_mode=true",
        task,
    ]
    return _run_logged_subprocess("codex exec", cmd, root, timeout=600)


@traceable(name="run_claude_exec")
def _run_claude_exec(task: str, cwd: Path) -> subprocess.CompletedProcess[str]:
    cmd: list[str] = ['claude', '--output-format', 'json', '--permission-mode', 'bypassPermissions']
    cmd.extend(["-p", task ])
    return _run_logged_subprocess("claude", cmd, str(cwd), timeout=600)


def _run_coding_agent_exec(task: str, cwd: Path) -> tuple[str, subprocess.CompletedProcess[str]]:
    tool = CODING_TOOL    
    if tool == "claude":
        return tool, _run_claude_exec(task, cwd)
    return tool, _run_codex_exec(task, cwd)


@traceable(name="run_simulation")
def _run_simulation(*, workspace: Path) -> subprocess.CompletedProcess[str]:
    cmd: list[str] = [
        sys.executable,
        str(SIMULATE_SCRIPT_PATH),
        "--entry",
        str(workspace / "strategy.py"),
    ]
    timeout_s = int(os.getenv("STRATEGY_BACKTEST_TIMEOUT_S", "1800"))
    freeze_timeout_s = int(os.getenv("STRATEGY_BACKTEST_FREEZE_TIMEOUT_S", "120"))
    return _run_logged_subprocess_with_freeze_watchdog(
        label="strategy simulation",
        cmd=cmd,
        cwd=str(workspace),
        timeout=timeout_s,
        freeze_timeout=freeze_timeout_s,
    )


@traceable(name="run_logged_subprocess_with_freeze_watchdog")
def _run_logged_subprocess_with_freeze_watchdog(
    *,
    label: str,
    cmd: list[str],
    cwd: str,
    timeout: int,
    freeze_timeout: int,
) -> subprocess.CompletedProcess[str]:
    if freeze_timeout <= 0:
        return _run_logged_subprocess(label, cmd, cwd, timeout=timeout)

    t0 = time.monotonic()
    last_progress = t0
    out_chunks: list[str] = []
    err_chunks: list[str] = []
    max_capture_chars = 200_000

    def _append(chunks: list[str], s: str) -> None:
        if not s:
            return
        chunks.append(s)
        total = sum(len(x) for x in chunks)
        while total > max_capture_chars and chunks:
            dropped = chunks.pop(0)
            total -= len(dropped)

    def _kill_process_tree(proc: subprocess.Popen[str]) -> None:
        try:
            pgid = os.getpgid(proc.pid)
        except Exception:
            pgid = None
        try:
            if pgid is not None:
                os.killpg(pgid, signal.SIGTERM)
            else:
                proc.terminate()
        except Exception:
            pass
        deadline = time.monotonic() + 3.0
        while time.monotonic() < deadline:
            if proc.poll() is not None:
                return
            time.sleep(0.05)
        try:
            if pgid is not None:
                os.killpg(pgid, signal.SIGKILL)
            else:
                proc.kill()
        except Exception:
            pass

    try:
        proc = subprocess.Popen(
            cmd,
            cwd=cwd,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            bufsize=1,
            universal_newlines=True,
            start_new_session=True,
        )
    except OSError as e:
        logger.error("%s failed to start: %s", label, e)
        raise

    sel = selectors.DefaultSelector()
    assert proc.stdout is not None
    assert proc.stderr is not None
    sel.register(proc.stdout, selectors.EVENT_READ, data="stdout")
    sel.register(proc.stderr, selectors.EVENT_READ, data="stderr")

    try:
        while True:
            rc = proc.poll()
            if rc is not None:
                try:
                    remaining_out, remaining_err = proc.communicate(timeout=0.2)
                except Exception:
                    remaining_out, remaining_err = "", ""
                _append(out_chunks, remaining_out or "")
                _append(err_chunks, remaining_err or "")
                break

            now = time.monotonic()
            if timeout > 0 and (now - t0) > timeout:
                _kill_process_tree(proc)
                raise subprocess.TimeoutExpired(cmd=cmd, timeout=timeout)

            if (now - last_progress) > freeze_timeout:
                _kill_process_tree(proc)
                raise subprocess.TimeoutExpired(cmd=cmd, timeout=freeze_timeout)

            events = sel.select(timeout=0.25)
            if not events:
                continue

            for key, _mask in events:
                stream_name = key.data
                try:
                    line = key.fileobj.readline()
                except Exception:
                    line = ""
                if not line:
                    continue
                last_progress = time.monotonic()
                if stream_name == "stdout":
                    _append(out_chunks, line)
                else:
                    _append(err_chunks, line)
    finally:
        try:
            sel.close()
        except Exception:
            pass

    stdout = "".join(out_chunks)
    stderr = "".join(err_chunks)
    completed = subprocess.CompletedProcess(args=cmd, returncode=proc.returncode or 0, stdout=stdout, stderr=stderr)
    if completed.returncode != 0:
        logger.error(
            "%s failed: returncode=%s\nstdout:\n%s\nstderr:\n%s",
            label,
            completed.returncode,
            _tail(completed.stdout or ""),
            _tail(completed.stderr or ""),
        )
    return completed


@traceable(name="run_workspace_command")
def _run_workspace_command(
    command: str,
    cwd: Path,
) -> subprocess.CompletedProcess[str]:
    parts = shlex.split(command)
    if parts and parts[0] == "python":
        parts[0] = sys.executable
    timeout_s = int(os.getenv("STRATEGY_BACKTEST_TIMEOUT_S", "1800"))
    return _run_logged_subprocess("workspace command", parts, str(cwd), timeout=timeout_s)


def read_strategy_name_from_workspace(root: Path) -> str:
    candidates = (
        root / "params.json",
        root / "backtest.json",
    )
    for path in candidates:
        if not path.is_file():
            continue
        try:
            raw = path.read_text(encoding="utf-8").strip()
            if not raw:
                continue
            data = json.loads(raw)
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(data, dict):
            n = data.get("strategy_name")
            if isinstance(n, str):
                s = n.strip()
                if s:
                    return s[:512]
    return ""


@traceable(name="run_update_strategy")
def run_update_strategy(
    thread_id: str, task: str, on_progress: ProgressCallback = None
) -> dict[str, Any]:
    task = (task or "").strip()
    if not task:
        return {"ok": False, "error": "task is empty"}
    if not thread_id_allowed(thread_id):
        return {"ok": False, "error": "invalid thread_id"}
    root = ensure_strategy_workspace(thread_id)
    ticker = (os.getenv("STRATEGY_BACKTEST_TICKER") or "SPY").strip() or "SPY"

    if on_progress:
        on_progress("Updating strategy, this may take a few minutes…")
    runner, codegen = _run_coding_agent_exec(STRATEGY_CODE_AGENT_PREFIX + task, root)
    logger.info(f"Coding agent exec result: {runner}, {codegen.returncode}, {codegen.stdout[:100]}, {codegen.stderr[:100]}")
    result: dict[str, Any] = {
        "runner": runner,
        "codex_returncode": codegen.returncode,
        "codex_stdout": _tail(codegen.stdout or ""),
        "codex_stderr": _tail(codegen.stderr or ""),
        "ok": codegen.returncode == 0,
    }
    if codegen.returncode != 0:
        result["error"] = "claude code failed" if runner == "claude" else "codex exec failed"
    else:
        result["strategy_name"] = read_strategy_name_from_workspace(root)
    return result


def _read_params_json_object(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        text = path.read_text(encoding="utf-8").strip()
        if not text:
            return {}
        data = json.loads(text)
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def read_strategy_description_from_workspace(root: Path) -> str:
    candidates = (
        root / "params.json",
    )
    for path in candidates:
        data = _read_params_json_object(path)
        if not data:
            continue
        desc = data.get("description")
        if isinstance(desc, str):
            s = desc.strip()
            if s:
                return s[:2048]
    return ""


def _deep_merge_json_values(base: Any, overlay: Any) -> Any:
    if isinstance(base, dict) and isinstance(overlay, dict):
        out = dict(base)
        for key, value in overlay.items():
            if key in out:
                out[key] = _deep_merge_json_values(out[key], value)
            else:
                out[key] = value
        return out
    if isinstance(base, list) and isinstance(overlay, list):
        length = max(len(base), len(overlay))
        merged: list[Any] = []
        for i in range(length):
            if i >= len(base):
                merged.append(overlay[i])
            elif i >= len(overlay):
                merged.append(base[i])
            else:
                merged.append(_deep_merge_json_values(base[i], overlay[i]))
        return merged
    return overlay


def _merge_parameters_json_into_params_file(root: Path, parameters_json: Any) -> None:
    if parameters_json is None:
        return

    parsed: Any
    if isinstance(parameters_json, str):
        raw = parameters_json.strip()
        if not raw:
            return
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            raise ValueError("parameters_json is not valid JSON")
    else:
        parsed = parameters_json

    root.mkdir(parents=True, exist_ok=True)
    params_path = root / "params.json"
    if isinstance(parsed, dict):
        existing = _read_params_json_object(params_path)
        to_write = _deep_merge_json_values(existing, parsed)
    else:
        to_write = parsed
    params_path.write_text(
        json.dumps(to_write, indent=2, sort_keys=True),
        encoding="utf-8",
    )


def _merge_parameters_hyperopt_json_into_params_hyperopt_file(
    root: Path, parameters_hyperopt_json: Any
) -> None:
    if parameters_hyperopt_json is None:
        return

    parsed: Any
    if isinstance(parameters_hyperopt_json, str):
        raw = parameters_hyperopt_json.strip()
        if not raw:
            return
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError:
            raise ValueError("parameters_hyperopt_json is not valid JSON")
    else:
        parsed = parameters_hyperopt_json

    root.mkdir(parents=True, exist_ok=True)
    path = root / "params-hyperopt.json"
    if isinstance(parsed, dict):
        existing = _read_params_json_object(path)
        to_write = _deep_merge_json_values(existing, parsed)
    else:
        to_write = parsed
    path.write_text(
        json.dumps(to_write, indent=2, sort_keys=True),
        encoding="utf-8",
    )


_REDACT_JSON_KEYS_FOR_USER = frozenset(
    {
        "openrouter_api_key",
        "langsmith_api_key",
        "openai_api_key",
        "alpaca_secret_key",
        "postgres_password",
    }
)


def _is_secret_json_key(key: str) -> bool:
    n = (key or "").strip().lower().replace("-", "_")
    return n in _REDACT_JSON_KEYS_FOR_USER


def redact_secret_json_values_for_user(obj: Any) -> Any:
    if isinstance(obj, dict):
        out: dict[Any, Any] = {}
        for k, v in obj.items():
            ks = str(k) if k is not None else ""
            if _is_secret_json_key(ks):
                out[k] = ""
            else:
                out[k] = redact_secret_json_values_for_user(v)
        return out
    if isinstance(obj, list):
        return [redact_secret_json_values_for_user(x) for x in obj]
    if isinstance(obj, str):
        stripped = obj.strip()
        if stripped.startswith("{") or stripped.startswith("["):
            try:
                parsed = json.loads(obj)
            except json.JSONDecodeError:
                return obj
            if isinstance(parsed, (dict, list)):
                redacted = redact_secret_json_values_for_user(parsed)
                return json.dumps(redacted, indent=2, sort_keys=True)
        return obj
    return obj


def _simulation_inputs_from_params(root: Path) -> tuple[str, str, float, str | None] | str:
    params = _read_params_json_object(root / "params.json")
    start_date = params.get("start_date")
    end_date = params.get("end_date")
    if not isinstance(start_date, str) or not start_date.strip():
        return "params.json is missing start_date (YYYY-MM-DD)"
    if not isinstance(end_date, str) or not end_date.strip():
        return "params.json is missing end_date (YYYY-MM-DD)"
    raw_deposit = params.get("initial_deposit", 10_000)
    try:
        deposit = float(raw_deposit)
    except (TypeError, ValueError):
        return "params.json initial_deposit must be a number"
    if deposit <= 0:
        return "params.json initial_deposit must be positive"
    provider_raw = params.get("provider")
    provider = provider_raw.strip() if isinstance(provider_raw, str) and provider_raw.strip() else None
    return start_date.strip(), end_date.strip(), deposit, provider


def _is_simulator_command(command: str) -> bool:
    parts = shlex.split(command or "")
    if not parts:
        return False
    if parts[-1] != "strategy.py":
        return False
    return len(parts) == 1 or parts[0] in ("python", "python3") or parts[0] == sys.executable


def _is_hyperopt_command(command: str) -> bool:
    parts = shlex.split(command or "")
    if not parts:
        return False
    if parts[-1] != "hyperopt.py":
        return False
    return len(parts) == 1 or parts[0] in ("python", "python3") or parts[0] == sys.executable


@traceable(name="run_backtest")
def run_backtest(
    thread_id: str,
    command: str,
    on_progress: ProgressCallback = None,
    parameters_json: Any = None,
    parameters_hyperopt_json: Any = None,
) -> dict[str, Any]:
    if not thread_id_allowed(thread_id):
        return {"ok": False, "error": "invalid thread_id"}
    command = (command or "").strip()
    if not command:
        return {"ok": False, "error": "command is empty"}
    root = ensure_strategy_workspace(thread_id)
    if parameters_json is not None:
        try:
            _merge_parameters_json_into_params_file(root, parameters_json)
        except ValueError as e:
            return {"ok": False, "error": str(e)}

    if parameters_hyperopt_json is not None and _is_hyperopt_command(command):
        try:
            _merge_parameters_hyperopt_json_into_params_hyperopt_file(
                root, parameters_hyperopt_json
            )
        except ValueError as e:
            return {"ok": False, "error": str(e)}

    if _is_simulator_command(command):
        resolved = _simulation_inputs_from_params(root)
        if isinstance(resolved, str):
            return {"ok": False, "error": resolved}
        start_date, end_date, deposit, provider = resolved
        if on_progress:
            on_progress("Running simulation…")
        try:
            bt = _run_simulation(workspace=root)
        except subprocess.TimeoutExpired as e:
            freeze_timeout_s = int(os.getenv("STRATEGY_BACKTEST_FREEZE_TIMEOUT_S", "120"))
            msg = f"backtest froze and was killed after {freeze_timeout_s}s without output"
            logger.error("%s: %s", "strategy simulation", msg)

            fix_attempt = run_update_strategy(
                thread_id,
                (
                    "The backtest froze and was killed due to no output for over 120 seconds. "
                    "Fix strategy.py so it cannot hang: remove infinite loops, ensure per-bar processing is fast, "
                    "avoid blocking network calls, and always read stdin line-by-line and emit outputs regularly per AGENTS.md. "
                    "Then keep the strategy logic intact as much as possible."
                ),
                on_progress=on_progress,
            )
            if fix_attempt.get("ok"):
                if on_progress:
                    on_progress("Retrying simulation after auto-fix…")
                bt = _run_simulation(workspace=root)
            else:
                return {
                    "ok": False,
                    "error": msg,
                    "backtest_returncode": 124,
                    "backtest_stdout": "",
                    "backtest_stderr": "",
                    "autofix": fix_attempt,
                }
        extras: dict[str, Any] = {
            "start_date": start_date,
            "end_date": end_date,
            "initial_deposit": deposit,
            "provider": provider or "auto",
        }
        failure_message = "simulation failed"
    else:
        if on_progress:
            on_progress("Optimizing strategy parameters…")
        bt = _run_workspace_command(command, root)
        extras = {}
        failure_message = "hyperopt failed"

    result: dict[str, Any] = {
        "command": command,
        **extras,
        "backtest_returncode": bt.returncode,
        "backtest_stdout": _tail(bt.stdout or ""),
        "backtest_stderr": _tail(bt.stderr or ""),
        "ok": bt.returncode == 0,
    }
    if bt.returncode != 0:
        result["error"] = failure_message
    return result


def _tool_handlers_for_thread(
    thread_id: str,
    *,
    on_progress: ProgressCallback = None,
) -> dict[str, Callable[[dict[str, Any]], dict[str, Any]]]:
    def _update(args: dict[str, Any]) -> dict[str, Any]:
        return run_update_strategy(thread_id, str(args.get("task", "")), on_progress=on_progress)

    def _run_backtest_tool(args: dict[str, Any]) -> dict[str, Any]:
        return run_backtest(
            thread_id,
            "python strategy.py",
            on_progress=on_progress,
            parameters_json=args.get("parameters_json"),
            parameters_hyperopt_json=None,
        )

    def _run_hyperopt_tool(args: dict[str, Any]) -> dict[str, Any]:
        return run_backtest(
            thread_id,
            "python hyperopt.py",
            on_progress=on_progress,
            parameters_json=args.get("parameters_json"),
            parameters_hyperopt_json=args.get("parameters_hyperopt_json"),
        )

    def _analyse(args: dict[str, Any]) -> dict[str, Any]:
        return run_analyse_code(
            thread_id=thread_id,
            question=str(args.get("question", "")),
        )

    return {
        UPDATE_STRATEGY_TOOL_NAME: _update,
        RUN_BACKTEST_TOOL_NAME: _run_backtest_tool,
        RUN_HYPEROPT_TOOL_NAME: _run_hyperopt_tool,
        ANALYSE_CODE_TOOL_NAME: _analyse,
    }


def _stored_messages_to_lc(messages: list[dict[str, Any]]) -> list[BaseMessage]:
    out: list[BaseMessage] = []
    for m in messages:
        role = str(m.get("role", ""))
        raw = m.get("content", "")
        if raw is None:
            content = ""
        elif isinstance(raw, str):
            content = raw
        else:
            content = str(raw)
        if role == "user":
            out.append(HumanMessage(content=content))
        elif role == "assistant":
            out.append(AIMessage(content=content))
    return out


def _aimessage_plain_text(msg: AIMessage) -> str:
    c = msg.content
    if c is None:
        return ""
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        parts: list[str] = []
        for block in c:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict) and block.get("type") == "text":
                parts.append(str(block.get("text", "")))
        return "".join(parts)
    return str(c)


def _tool_call_parts(tc: Any) -> tuple[str, dict[str, Any], str]:
    if isinstance(tc, dict):
        name = str(tc.get("name", "") or "")
        tid = str(tc.get("id", "") or "")
        args = tc.get("args")
        if args is None and "function" in tc:
            fn = tc.get("function") or {}
            raw = fn.get("arguments") if isinstance(fn, dict) else None
            if isinstance(raw, str):
                try:
                    args = json.loads(raw or "{}")
                except json.JSONDecodeError:
                    args = {}
            else:
                args = raw if isinstance(raw, dict) else {}
        if not isinstance(args, dict):
            args = {}
        return name, args, tid
    name = str(getattr(tc, "name", "") or "")
    tid = str(getattr(tc, "id", "") or "")
    args = getattr(tc, "args", None)
    if not isinstance(args, dict):
        args = {}
    return name, args, tid

@traceable(name="build_agent_reply")
def build_agent_reply(
    messages: list[dict[str, Any]],
    existing_canvas: dict[str, Any],
    thread_id: str,
    on_progress: ProgressCallback = None,
) -> dict[str, Any]:
    t0 = time.perf_counter()

    def _reply_duration_ms() -> int:
        return int(round((time.perf_counter() - t0) * 1000))

    if not os.getenv("OPENROUTER_API_KEY", "").strip():
        return {
            "message": (
                "OPENROUTER_API_KEY is not configured. Your message was saved. "
                "Set the key to enable live agent responses."
            ),
            "canvas": canvas_with_output(existing_canvas, thread_id),
            "reply_duration_ms": _reply_duration_ms(),
            "strategy_name": "",
        }

    workspace = strategy_root_for_thread(thread_id)
    params_path = workspace / "params.json"
    strategy_parameters = ""
    if params_path.is_file():
        try:
            strategy_parameters = params_path.read_text(encoding="utf-8", errors="replace").strip()
        except OSError:
            strategy_parameters = ""
    hyperopt_path = workspace / "params-hyperopt.json"
    hyperopt_parameters = ""
    if hyperopt_path.is_file():
        try:
            hyperopt_parameters = hyperopt_path.read_text(encoding="utf-8", errors="replace").strip()
        except OSError:
            hyperopt_parameters = ""
    metrics_path = workspace / "metrics.json"
    metrics_text = ""
    if metrics_path.is_file():
        try:
            metrics_text = metrics_path.read_text(encoding="utf-8", errors="replace").strip()
        except OSError:
            metrics_text = ""
    hyperopt_section = (
        f"\nThe current strategy supports hyperparameter optimization. The params-hyperopt.json file contains the optimization configuration:\n{hyperopt_parameters}\n"
        if hyperopt_parameters
        else ""
    )
    metrics_section = (
        f"\nLatest metrics from metrics.json:\n{metrics_text}\n"
        if metrics_text
        else ""
    )
    if params_path.is_file():
        strategy_help = f"""Strategy inputs are read from params.json (overrides: pass parameters_json on run_backtest or run_hyperopt to merge into this file). On run_hyperopt, optional parameters_hyperopt_json merges into params-hyperopt.json (which params are optimised, ranges, regimes, study budget—not ticker/dates from params.json).
{strategy_parameters}
{hyperopt_section}{metrics_section}"""
    else:
        strategy_help = f"""Note: params.json hasn't been created yet. Need to run update_strategy first.

Current params.json (may be empty or missing):
{strategy_parameters}
On run_hyperopt, optional parameters_hyperopt_json merges into params-hyperopt.json (study definition: optimised params, ranges, regimes—not params.json backtest inputs).
{hyperopt_section}{metrics_section}"""
    chat_messages: list[BaseMessage] = [
        SystemMessage(content=SYSTEM_PROMPT.format(strategy_help=strategy_help)),
        *_stored_messages_to_lc(messages),
    ]

    max_iterations = 10
    last_strategy_name = ""
    llm = ChatOpenRouter(model=CHAT_MODEL, request_timeout=120_000, reasoning={"effort": CHAT_REASONING_EFFORT})
    llm_tools = llm.bind_tools(AGENT_TOOLS)
    tool_handlers = _tool_handlers_for_thread(
        thread_id,
        on_progress=on_progress,
    )

    for _ in range(max_iterations):
        if on_progress:
            on_progress("Thinking…")
        assistant_msg = llm_tools.invoke(chat_messages)
        chat_messages.append(assistant_msg)
        tool_calls = assistant_msg.tool_calls or []
        if not tool_calls:
            content = _aimessage_plain_text(assistant_msg).strip()
            if not content:
                raise Exception(
                    "The model returned an empty message. Try again or adjust CHAT_MODEL; "
                    "empty content can happen when a provider blocks the request or returns no completion."
                )
            return {
                "message": content,
                "canvas": canvas_with_output(existing_canvas, thread_id),
                "reply_duration_ms": _reply_duration_ms(),
                "strategy_name": last_strategy_name,
            }
        for tc in tool_calls:
            name, parsed_args, tid = _tool_call_parts(tc)
            handler = tool_handlers.get(name)
            if handler is None:
                tool_payload: dict[str, Any] = {"ok": False, "error": f"unknown tool: {name}"}
            else:
                try:
                    tool_payload = handler(parsed_args)
                except Exception as e:
                    logger.exception(
                        "tool execution failed",
                        extra={
                            "thread_id": thread_id,
                            "tool_name": name,
                            "tool_call_id": tid,
                            "tool_args": parsed_args,
                        },
                    )
                    tool_payload = {"ok": False, "error": f"tool execution failed: {type(e).__name__}: {e}"}
            if (
                name == UPDATE_STRATEGY_TOOL_NAME
                and isinstance(tool_payload, dict)
                and tool_payload.get("ok")
            ):
                sn = tool_payload.get("strategy_name")
                if isinstance(sn, str) and sn.strip():
                    last_strategy_name = sn.strip()[:512]
            limited = tool_payload
            if name == UPDATE_STRATEGY_TOOL_NAME:
                limited = _trim_tool_payload_streams(
                    tool_payload,
                    UPDATE_STRATEGY_TOOL_MESSAGE_MAX_JSON,
                    "codex_stdout",
                    "codex_stderr",
                )
            elif name in (RUN_BACKTEST_TOOL_NAME, RUN_HYPEROPT_TOOL_NAME):
                limited = _trim_tool_payload_streams(
                    tool_payload,
                    RUN_EXECUTION_TOOL_MESSAGE_MAX_JSON,
                    "backtest_stdout",
                    "backtest_stderr",
                )
            chat_messages.append(
                ToolMessage(content=json.dumps(limited), tool_call_id=tid)
            )

    raise Exception("Agent stopped: maximum tool iterations reached without a final reply.")
