server {
  listen 8080;

  include /etc/nginx/mime.types;
  types {
    application/javascript mjs;
  }

  root /usr/share/nginx/html;
  index index.html;

  location ~* \.mjs$ {
    default_type application/javascript;
    try_files $uri =404;
  }

  location /api/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 3600s;
    proxy_send_timeout 3600s;
    proxy_pass http://vibetrader-backend:8080/;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}

